config/routes.rb
Rails.application.routes.draw do
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :users
  resources :plates do
    resources :comments
  end

  post "/plate/find" => 'plates#show', as: :plate_show

  root :to => "welcome#index"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :plate
	belongs_to :user
end

app/models/plate.rb
class Plate < ActiveRecord::Base
	has_many :comments
	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/gif", "image/png"]

  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def index
         @comments = Comment.all
    end


    def show
        @comment = Comment.find(params[:id])
    end


    def new
        @comment = Comment.new
        
    end

    def create
        @comment = Comment.new({
            body: comment_params[:body],
            plate_id: params[:plate_id]
            })


        if @comment.save
            redirect_to plate_path(params[:plate_id])
        else
            render :new
        end
    end


    def edit
        @comment = Comment.find(params[:id])
    end


    def update
        @comment = Comment.find(params[:id])

       	if @comment.update_attributes(comment_params)
            redirect_to wines_path
        else
             render :edit
        end
    end


    def destroy
         @comment = Comment.find(params[:id])
         @comment.destroy
         redirect_to comments_path
    end

    private
    def comment_params
        params.require(:comment).permit( :body )
    end

end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController

    def index
        @plates = Plate.all
    end

    def show
        #Find the plate
        if params[:id]
        @plate = Plate.find( params[:id] )
        end
        if( @plate == nil )
            @plate = Plate.where({ plate_state: params[:plate][:plate_state], plate_number: params[:plate][:plate_number] }).first
        end
        #  # If plate does not exists, set @plate to a new plate (create)
        if @plate == nil
            @plate = Plate.create({plate_state: params[:plate][:plate_state], plate_number: params[:plate][:plate_number] })
        end
    end


    def new
        @plate = Plate.new
    end


    def create
        @plate = Plate.new(plate_params)

        if @plate.save
            redirect_to plates_path
        else
            render :new
        end
    end


    def edit
         @plate = Plate.find(params[:id])
    end


    def update
         @plate = Plate.find(params[:id])

        if @plate.update_attributes(plate_params)
            redirect_to plates_path
        else
            render :edit
        end
    end


    def destroy
         @plate = Plate.find(params[:id])
         @plate.destroy
         redirect_to plates_path
    end

    private
    def plate_params
        params.require(:plate).permit(:plate_number, :plate_state, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end


  def create
  	user = User.find_by(email: params[:login][:email])

  		if user && user.authenticate(params[:login][:password])
  			session[:user_id] = user.id.to_s
  			redirect_to users_path
  		else
  			render :new
  	end	
  end


  def destroy
  	session.delete(:user_id)
  	redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end


	def new
		@user = User.new
	end


	def create
		@user = User.new(params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation))

		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to users_path
		else
			render :new
		end
	end


	def edit
		@user = User.find(params[:id])
	end


	def update
		@user = User.find(params[:id])

		if @user.update_attributes(parmas.requre(:user).permit(:fname, :lname, :email, :password, :password_confirmation))
			redirect_to users_path
		else
			render :edit
		end
	end


    def destroy
         @user = User.find(params[:id])
         @user.destroy
         redirect_to users_path
    end

    private
    def users_params
    	params.require(:user).permit(:image,:fname, :lname, :email, :password, :password_confirmation)

    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
 	 @current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
    	!current_user.nil?
  	end
  	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@plate, Comment.new] do |form| %>
	<%= form.text_field :body %>
	<%= form.submit %>
	</br>
	</br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlateApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if current_user %>
	You are logged in as <%= current_user.fname %></br>
	<%= link_to "Log Out", logout_path, method: :delete %>

<% end %>



<%= yield %>

<%#= params %>
</body>
</html>

app/views/plates/index.html.erb
<h1>RoaD RageR: </h1>
<h2>To check for comments please enter State Two Digit Code and Plate #:</h2>

<%= form_for :plate, :url => "/plate/find/" do |form| %>
	<%= form.text_field :plate_state, :placeholder => "State Code" %></br>
	<%= form.text_field :plate_number, :placeholder => "License Plate ID" %></br>
	<%= form.submit "Find Plate"%></br></br>
<% end %>

app/views/plates/new.html.erb
<!-- <h1>RoaD RageR: </h1>
<h2>Register New Plate by Entering State Code & Plate #</h2>

<%= form_for @plate do |form| %>
	<%= form.text_field :plate_state, :placeholder => "State Code" %>
</br>
	<%= form.text_field :plate_number, :placeholder => "License Plate ID" %>
</br>
	<%= form.submit "Find" %>
</br>
</br>
<% end %> -->

app/views/plates/show.html.erb
<h1>RoaD RageR Comments</h1>

<br />


<h5><%= @plate.plate_state %></h5>
<h5><%= @plate.plate_number %></h5>

<ul>
<% @plate.comments.each do |comment| %>
	<li><%= comment.body %></li>
<% end %>
</ul>

</br>
</br>

Leave your own RoaD RageR comment? First, sign up:
</br>
<%= link_to "Sign Up", new_user_path %>

</br>
</br>

RoaD RageR members must log in to leave a comment:
</br>
<%= link_to "Log In", login_path %>

</br>
</br>

View RoaD RageR user comments about other person(s)/plates:
</br>
<%= link_to "View Plates", plates_path %>
</br>
</br>

 <% if current_user != nil %>
 <h3>Make a RoaD RageR comment here:</h3>
 	<%= render 'comments/form' %>
<% end %>

app/views/users/index.html.erb
<h1>RoaD RageR</h1>

<h1>Welcome <%= current_user.fname %></h1>

<h2>You are ready to begin Raging</h2>

View RoaD RageR comments about your/other's plate:
</br>
<%= link_to "View Plates", plates_path %>
</br>
</br>

app/views/users/new.html.erb
<h1>RoaD RageR: Sign Me Up!</h1>

<%= form_for @user do |form| %>
	<%= form.text_field :fname, :placeholder => "First Name" %></br>
	<%= form.text_field :lname, :placeholder => "Last Name" %></br>
	<%= form.text_field :email, :placeholder => "Email" %></br>
	<%= form.password_field :password, :placeholder => "Password" %></br>
	<%= form.password_field :password_confirmation, :placeholder => "Password (Enter Again)" %></br></br>

	<%= form.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>RoaD RageR</h1>
<h2>Welcome</h2>

<p> Have you ever been stuck in stop and go traffic on the freeway behind someone with no brake lights?  With no ability to notify them? You may have felt some Road Rage!
</p>

<p> Did someone park so close to your driver door you couldn't get in and had to climb through the passenger side? You may have felt some Road Rage and wanted to key their car like Edward Scissorhands!
</p>

<p> Channel your energy a little more positively, and notify them of a serious problem or just tell them off(nicely) via Road Rager! Of course, it requires everyone sign up, but it is easier and requires less time and/or money than a therapist or night in jail for a case of ROAD RAGE!
</p>

<p>
<h5>Check to see if anyone has left you any RoaD RageR messages:<h5></br>
<%= link_to "View Plates", plates_path %>
</br></br>

<h5>Send RoaD RageR messages to other drivers, after a simple sign up!<h5></br>
<%= link_to "Sign Up Page", new_user_path %>
</br></br>

<h5>Already a Road Rager member?<h5></br>
<%= link_to "Log In Page", login_path %>

</p>